name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  dots_indicator: ^3.0.0
  carousel_slider: ^4.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  get_it: ^7.6.7
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
